db/migrate/20181024114437_add_admin_to_users.rb, db/schema.rb
We need to be able to distinguish bewteen normal and admin users, the
simplist way of doing this for MVP is by adding a boolean to the users
table.  If more roles are required later we will address this then.
=> GI-13 Add Admin to Users table

spec/requests/ideas_spec.rb
Improve ideas request spec to add admin user and test if users button is / isn't present.
=> Add admin to ideas request spec

Gemfile, Gemfile.lock
Warning on github about this CVE.
https://nvd.nist.gov/vuln/detail/CVE-2018-16468
This update fixes.
=> Fix CVE-2018-16468

app/models/user.rb, app/validators/email_validator.rb, spec/controllers/ideas_controller_spec.rb, spec/models/user_spec.rb, spec/requests/ideas_spec.rb, spec/requests/users_spec.rb, spec/system/assign_idea_spec.rb, spec/system/idea_submission_spec.rb, spec/system/sign_up_spec.rb, spec/system/user_admin_spec.rb
When signing up the users email address should only be valid if the
email address is from the justice.gov.uk domain. This includes the
digital.justice.gov.uk domain and other subdomains.
To verify this validation in the real world, email confirmation will
need to be turned on in Devise.  This will be done in a separate PR.
Existing tests have been updated to use valid email addresses.
=> GI-9 Validate email is from justice.gov.uk domain

app/views/layouts/application.html.erb, config/routes.rb, spec/requests/users_spec.rb, spec/system/sign_out_spec.rb
Log out link added to top of all pages if the current user is logged in.
This should be moved later to a better position eg nav bar when we have
one.
Also tidied up the urls for the users/sign_in etc to just /sign_in as
the user part at the start is a little untidy.
=> GI-57 Add log out link

Gemfile, Gemfile.lock, app/mailers/notify_mailer.rb, config/environments/test.rb, config/initializers/gov_uk_notify.rb, spec/mailers/notify_mailer_spec.rb, spec/system/email_spec.rb
This adds Gov.uk notify email messaging.  The GOVUK_NOTIFY_API_KEY
environment variable should be set before starting the server for the
emails to work.
API Keys should be stored securely, there is a test key (doesn't send
email) and a whitelist key (sends to team members on notify).
When tests are running the perform_deliveries = false prevents
deliveries from being made externally.
The email_spec.rb is largely redundant when this setting is enabled but
I will leave it here for the moment as it is useful to test the notify
service until we have something else in the app that sends an email, by
setting the perform_deliveries to true (or commenting out)
The notify mailer is currently configured to send a simple template,
this will be updated in future PRs to add in personalisation and …
=> Add email functionality to app

Gemfile, Gemfile.lock, spec/factories/comments.rb, spec/factories/ideas.rb, spec/factories/users.rb, spec/models/user_spec.rb, spec/rails_helper.rb, spec/requests/comments_spec.rb, spec/requests/ideas_spec.rb, spec/requests/users_spec.rb, spec/system/add_comment_spec.rb, spec/system/assign_idea_spec.rb, spec/system/email_spec.rb, spec/system/idea_submission_spec.rb, spec/system/sign_out_spec.rb, spec/system/update_status_spec.rb, spec/system/user_admin_spec.rb
Using instance variables was becoming unmanageble and the need to use the
factory pattern was hightlighted when I wanted to add devise token to
users, it would of meant updating each instance variable individually.
Now you can just update the factory.
=> GI-68 Introduced FactoryBot for tests

app/controllers/ideas_controller.rb, app/models/idea.rb, app/views/ideas/_form.html.erb, app/views/ideas/show.html.erb, db/migrate/20181205085733_add_review_date_to_ideas.rb, db/migrate/20181205095926_add_participation_level_to_ideas.rb, db/schema.rb, spec/requests/ideas_spec.rb, spec/system/assign_idea_spec.rb
What
As an admin I'd like to be able to edit and add information to an idea so I can start actioning it
Ticket
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?projectKey=GI&rapidView=250&selectedIssue=GI-22
Why
To introduce extra required admin only fields (Participation level and Review date)
How
Added participation_level to the ideas model
Added review_date to the ideas model
Made associated view and controller changes
Added request and system spec tests for changes
=> Add review_date and participation_level admin fields

app/controllers/registrations_controller.rb, app/mailers/devise_custom_mailer.rb, app/models/user.rb, app/views/comments/index.html.erb, app/views/comments/show.html.erb, app/views/devise/sessions/new.html.erb, app/views/ideas/index.html.erb, app/views/ideas/show.html.erb, app/views/layouts/application.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, config/environments/test.rb, config/initializers/devise.rb, config/routes.rb, spec/controllers/ideas_controller_spec.rb, spec/factories/users.rb, spec/system/sign_up_spec.rb
This change integrates the notify mailer with devise by creating a
custom mailer. The flash message was not being passed to the page after
signing up, as this was redirecting through to the home page, then
redirecting back to the sign in page.  To fix this the registrations
controller in devise is overridden, and a new flash message is passed
in.
User model updated to be confirmable (part of devise confirmations)
Devise mailer config changed
Mail url default options set for dev, not having this set was causing tests to fail.
User factory updated so that created users are already confirmed
Routes updated with new controller
=> GI-56 Integrate email with devise for confirmation

db/seeds.rb
After updating authentication with devise to require user confirmation,
the seed data was not updated, so all seed users are currently unconfirmed.
This will fix this.
=> Fix seed data to include user confirmation

app/controllers/comments_controller.rb, app/models/idea.rb, app/views/ideas/show.html.erb, db/seeds.rb, spec/factories/ideas.rb, spec/requests/comments_spec.rb, spec/system/add_comment_spec.rb
We do not want comments to be added to an idea until the idea has been approved.
From this point onwards they are publicly viewable and can be commented on.
=> GI-75 Only Approved ideas can have comments

app/models/idea.rb, app/views/ideas/show.html.erb, db/migrate/20190114094201_add_default_status_to_ideas.rb, db/schema.rb, spec/requests/ideas_spec.rb
We want to know which ideas have not been approved (ie and admin has
approved them) we have an awaiting_approval status for ideas which have
been submitted but there was no status for initially created ideas.  By
giving new ideas a draft default status, it is much clearer.
=> GI-70 add default status of draft for ideas

Dockerfile, README.md
This was missed when updating the ruby version, the docker build now
uses ruby-2.6.0 image.  Updated the readme to use bundle exec for
running rake command in the docker container.
=> Update Docker Ruby version

app/views/layouts/application.html.erb
I’ve added a mailto to the feedback link on the phase banner. I set it to send emails to the newly created laa-great-ideas@digital.justice.gov.uk.
We can change it to the actual email address used by the business before we host.
=> added mailto to feedback href

app/controllers/comments_controller.rb, app/helpers/comments_helper.rb, app/views/comments/new.html.erb, app/views/ideas/show.html.erb, spec/requests/comments_spec.rb
We want only admins to be able to comment on not proceeding ideas.
Refactored the .approved_by_admin? logic to a helper class, as it is
starting to get complex.  We can also use this helper class to introduce
further methods such as user_can_edit_comment for future stories.
=> GI-79 Only admins can comment on not_proceeding

db/seeds.rb
Faker was occasionally providing the same name and the unique email
validation was causing the seed load to fail. This prevents the email
from being a duplicate and also gives a more realistic email address
with firstname.lastname
=> Ensure email addresses in seeds are unique

helm_deploy/laa-great-ideas/templates/job.yaml
The pipeline was missing database migrations, this adds in a database
migration job pre helm install or upgrade.  So if this db migration fails for any reason the deployment will not take place.
Not entirely sure how to test that this is running migrations correctly though, still thinking about that, any suggestions welcome.
=> Add db:migrate to helm job

app/controllers/comments_controller.rb, app/controllers/ideas_controller.rb, app/views/comments/_comment_list.html.erb, app/views/comments/show.html.erb, spec/requests/comments_spec.rb
Changed comments to include users when getting records so that we can
show the user email address without querying the DB again.
Also removed idea from the comments table as you are already on the idea
when you view this.
Tests updated to reflect the comment must include a user as well.
=> GI-81 Fix comments showing user and idea ID

spec/system/update_review_date_spec.rb
Coverage was fine, then randomly wasn't as the rescue wasn't
being called.
This just adds in a test to make sure the rescue works when an exception
is raised.
=> Fix coverage issue with review dates

.circleci/config.yml
We need to ensure the build and test stage has completed before
deploying to the staging environment
=> Add requires build_and_test to staging

app/mailers/idea_mailer.rb, app/models/idea.rb, spec/mailers/idea_mailer_spec.rb, spec/rails_helper.rb, spec/system/update_status_spec.rb
Send an email when the status of an idea is updated
GI-47 https://dsdmoj.atlassian.net/jira/software/projects/GI/boards/250?selectedIssue=GI-47
So that people who have submitted an idea know that the status of the idea their idea has changed.
1. Added a new template to gov.uk notify
2. Created new method in idea_mailer.rb to generate an email based on the new template id.
3. Changed after_update on idea to call the new idea_mailer method.
4. Added system and idea_mailer specs.
=> Add functionality to send email when the status of an idea is updated

app/controllers/application_controller.rb, app/controllers/comments_controller.rb, app/controllers/ideas_controller.rb, config/locales/en.yml, spec/system/edit_idea_spec.rb
We were customising the error message in the controller, but this could
only be done once for all the actions.  This method enables us to have a
different error message for each action.
=> Switch to translation for pundit

app/views/ideas/show.html.erb, spec/system/add_comment_spec.rb, spec/system/add_vote_spec.rb, spec/system/assign_idea_spec.rb, spec/system/idea_submission_spec.rb, spec/system/update_status_spec.rb
Just noticed that the author was not on the show page, this would make
it difficult for admin users looking at ideas to easily see who created
the idea.
Tests updated as they were failing without a valid user associated with
and idea.
=> Add author to idea show page

app/controllers/comments_controller.rb, app/policies/comment_policy.rb, app/views/comments/_comment_list.html.erb, app/views/comments/show.html.erb, config/locales/en.yml, db/migrate/20190305133226_add_redacted_to_comments.rb, db/schema.rb, db/seeds/non_prod_seeds.rb, spec/factories/comments.rb, spec/requests/comments_spec.rb, spec/system/delete_comment_spec.rb
Add validation for delete comments.  Users can delete their own comment,
and admin users can delete anyones comment.
When a comment is deleted it is actually redacted, so the page displays
"This comment has been deleted" but the comment still exists in the
database only with a redacted flag set to true.
=> GI-131 Validation for delete comments

app/controllers/ideas_controller.rb, app/views/layouts/application.html.erb, spec/requests/ideas_spec.rb
The links for my ideas and for submitted ideas are no longer needed as
the tab functionality replaces this.
=> Remove unused links
