app/models/idea.rb, app/views/ideas/_form.html.erb, spec/models/idea_spec.rb
Add Area of Interest and Business Area enums to the Idea model
=> Add area of interest and business area enums

app/controllers/ideas_controller.rb, config/routes.rb, db/migrate/20181018101040_add_submit_date_to_ideas.rb, db/schema.rb, spec/requests/ideas_spec.rb
Add submission date to ideas (and test for deleting ideas)
=> Add submission date to ideas

app/controllers/users_controller.rb, app/views/ideas/index.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, config/routes.rb, spec/requests/users_spec.rb
Adds the ability for an admin to view details of a particular user.
Also added navigation links to get to user pages (admin only).
=> GI-16 View a user profile (admin only)

.circleci/config.yml, README.md, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, config/initializers/assets.rb, package-lock.json, package.json
Main application style configured with https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-with-npm.md
=> GI-39 Add GDS styling

Dockerfile, README.md, config/database.yml, docker-compose.yml
We would like to host Great Ideas on the MoJ Cloud Platform.  This uses
docker and kubernetes, the first step to achieving this is to have the
app and database run through docker compose.
=> GI-50 - Set up Docker Compose

app/controllers/ideas_controller.rb, spec/requests/ideas_spec.rb
Passing in the submitted parameter now gives a view of only submitted
ideas
=> GI-19 As admin, see list of submitted ideas

app/controllers/comments_controller.rb, app/models/comment.rb, app/models/idea.rb, app/models/user.rb, app/views/comments/_form.html.erb, app/views/comments/edit.html.erb, app/views/comments/index.html.erb, app/views/comments/new.html.erb, app/views/comments/show.html.erb, app/views/ideas/show.html.erb, config/routes.rb, db/migrate/20181123140831_create_comments.rb, db/schema.rb, spec/models/comment_spec.rb, spec/requests/comments_spec.rb, spec/requests/ideas_spec.rb, spec/system/add_comment_spec.rb
Add comment functionality, comments require a user (the signed in user)
and an idea (passed as a parameter).
Still to do
- add comments to the idea show view
- control who can edit comments
- tidy up comment views (front end stuff)
=> GI-24 Add comments

Gemfile, Gemfile.lock, README.md, db/seeds.rb
This adds seed data to the app using faker. This will make it easier to
test and demo the application.
=> GI-69 Add seed data

app/controllers/ideas_controller.rb, app/views/comments/_comment_list.html.erb, app/views/comments/edit.html.erb, app/views/comments/index.html.erb, app/views/comments/show.html.erb, app/views/ideas/show.html.erb, spec/system/add_comment_spec.rb
As a user I want to be able to see comments for an idea on the idea
page, this allows that to happen.  Also fixed the navigation so that it
makes more sense.
=> GI-67 Add comments to the idea show page

.editorconfig, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, db/schema.rb
GI-93 Added styling to the navigation items on the header banner and displayed horizontally(also changed font colour to white for ease of use).
=> Nav banner

app/views/layouts/application.html.erb
This link was previously visible as it was missing a embedded ruby if statement to check for current user. Now it will be hidden for those not signed in.
=> hid new idea link for users not signed in.

app/views/devise/confirmations/new.html.erb
Added styling to the embedded ruby to closely follow GDS standards
=> GI-86 Added styling for "resend confirmation" page

app/assets/stylesheets/application.scss, app/assets/stylesheets/ideas.scss, app/views/layouts/application.html.erb
Added govuk red for error messages and green for success for follow closely to GDS standards
=> added styling to flash messages

app/views/users/show.html.erb
Put details of user in a table so admins will be able to see details of a user more clearly
=> styled show user page

app/views/users/index.html.erb
styled table of users to fit with GDS standards.
=> added table styling to list of users

app/views/comments/_form.html.erb, app/views/ideas/_form.html.erb, spec/system/assign_idea_spec.rb, spec/system/update_status_spec.rb
Changed Submit to Create Idea and to Update Idea for more clarity for the users
=> updated text on submit and edit  buttons

app/views/ideas/show.html.erb
GI- 63 add styling to the show idea page to follow GDS standards
=> added styling to show idea page

app/views/comments/_comment_list.html.erb, app/views/comments/_form.html.erb, app/views/comments/edit.html.erb, app/views/comments/index.html.erb, app/views/comments/new.html.erb, app/views/comments/show.html.erb, app/views/ideas/show.html.erb
added GDDS styling to all comments pages.
=> GI-99 add styling for comments

app/controllers/comments_controller.rb, app/controllers/concerns/votable.rb, app/controllers/ideas_controller.rb, app/controllers/votes_controller.rb, app/models/idea.rb, app/models/user.rb, app/models/vote.rb, app/views/ideas/_review_date_and_uncompleted_ideas_table.html.erb, app/views/ideas/show.html.erb, config/routes.rb, db/migrate/20190118145417_create_votes.rb, db/migrate/20190124115930_change_null_columns_on_votes.rb, db/schema.rb, db/seeds.rb, spec/factories/votes.rb, spec/models/idea_spec.rb, spec/models/user_spec.rb, spec/models/vote_spec.rb, spec/requests/votes_spec.rb, spec/system/add_vote_spec.rb
This adds the ability for users to vote on any ideas which have been
approved by an admin.
User should only be able to vote on an idea once, and should only be
able to remove their own votes from an idea.
=> GI-25 Users can vote on ideas

app/helpers/application_helper.rb, app/views/comments/edit.html.erb, app/views/comments/index.html.erb, app/views/comments/new.html.erb, app/views/comments/show.html.erb, app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/unlocks/new.html.erb, app/views/ideas/edit.html.erb, app/views/ideas/new.html.erb, app/views/ideas/show.html.erb, app/views/layouts/application.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb
Page titles now show what page you are on to give a better user experience
=> GI-83 Make page titles nicer

helm_deploy/laa-great-ideas/.helmignore, helm_deploy/laa-great-ideas/Chart.yaml, helm_deploy/laa-great-ideas/README.md, helm_deploy/laa-great-ideas/templates/NOTES.txt, helm_deploy/laa-great-ideas/templates/_helpers.tpl, helm_deploy/laa-great-ideas/templates/deployment.yaml, helm_deploy/laa-great-ideas/templates/ingress.yaml, helm_deploy/laa-great-ideas/templates/service.yaml, helm_deploy/laa-great-ideas/templates/tests/test-connection.yaml, helm_deploy/laa-great-ideas/values.yaml
This changes adds the configuration files required for deploying via
helm for UAT. This is the next step before adding to the CircleCI
pipeline.  These files will likely change when adding to the pipeline.
=> Add helm for cloud platform deployment

app/assets/stylesheets/forms.scss, app/views/ideas/show.html.erb
Added CSS to the voting functionality on the show idea page and minor changes to the layout which may not be compliant to the GDS standards.
=> Vote functionality styling

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/policies/application_policy.rb
This will enable us to manage the growing authorisation requirements.
These requirements are listed in separate cards and will be addressed in
separate pull requests.
=> GI-114 Add pundit for authorisation

app/controllers/comments_controller.rb, app/models/comment.rb, spec/requests/comments_spec.rb
We want to record the status at the time of the comment to help put the
comment into context.
=> GI-104 Add status at time of comment

app/controllers/ideas_controller.rb, app/policies/idea_policy.rb, app/views/ideas/show.html.erb, spec/factories/ideas.rb, spec/requests/ideas_spec.rb, spec/system/edit_idea_spec.rb
Also add restriction so that users can only edit their own ideas.
=> GI-74 only admins can edit submitted ideas

Gemfile.lock, app/controllers/ideas_controller.rb, app/models/benefit.rb, app/models/idea.rb, app/views/ideas/_form.html.erb, app/views/ideas/show.html.erb, config/locales/en.yml, db/migrate/20190219161229_create_benefits.rb, db/schema.rb, db/seeds/non_prod_seeds.rb, spec/factories/benefits.rb, spec/factories/ideas.rb, spec/models/benefit_spec.rb, spec/models/idea_spec.rb, spec/requests/ideas_spec.rb, spec/system/create_idea_spec.rb
Change benefits from a drop down list to use multiple checkboxes.
=> GI-72 Benefits are checkboxes

app/models/idea.rb, app/validators/area_of_interest_validator.rb, db/seeds/non_prod_seeds.rb, spec/factories/ideas.rb, spec/models/idea_spec.rb, spec/requests/ideas_spec.rb, spec/system/edit_idea_spec.rb
What
Added validation to it system and business area to idea
Ticket
GI-117 https://dsdmoj.atlassian.net/jira/software/projects/GI/boards/250?selectedIssue=GI-117
Why
validatiobn
How
Added area_of_interest_validator for it_system and business_area
Added request and spec system tests
Fixed existing failing tests
=> Add validation for business area and it system to idea

helm_deploy/laa-great-ideas/templates/ingress.yaml
Fix our ingress config following a change from cloud-platform.
https://mojdt.slack.com/archives/CH6D099DF/p1554135480007100
=> Fix ingress host
